import {
  NotionDatabaseItem,
  NotionPropertyAsCheckbox,
  NotionPropertyAsCreatedTime,
  NotionPropertyAsDate,
  NotionPropertyAsLastEditedTime,
  NotionPropertyAsRichText,
  NotionPropertyAsTitle,
  NotionPropertyAsUrl,
} from './Notion'

export type NotionPepJob = NotionDatabaseItem<{
  ApplicantCriteria_Country_: NotionPropertyAsRichText
  ApplicantCriteria_EducationLevel_: NotionPropertyAsRichText
  ApplicantCriteria_ExperienceLevel_: NotionPropertyAsRichText
  Author: NotionPropertyAsRichText
  Created: NotionPropertyAsCreatedTime
  /** Automatically filled by Notion */
  CreeLe: NotionPropertyAsCreatedTime
  FirstPublicationDate: NotionPropertyAsRichText
  FirstPublicationDateFormated: NotionPropertyAsDate
  JobDescriptionTranslation_ContractLength_: NotionPropertyAsRichText
  JobDescriptionTranslation_Description1_: NotionPropertyAsRichText
  JobDescriptionTranslation_Description2_: NotionPropertyAsRichText
  JobDescriptionTranslation_JobTitle_: NotionPropertyAsRichText
  JobDescription_Contract_: NotionPropertyAsRichText
  JobDescription_Country_: NotionPropertyAsRichText
  JobDescription_CustomFieldsTranslation_LongText1_: NotionPropertyAsRichText
  JobDescription_CustomFieldsTranslation_LongText2_: NotionPropertyAsRichText
  JobDescription_CustomFieldsTranslation_LongText3_: NotionPropertyAsRichText
  JobDescription_CustomFieldsTranslation_ShortText2_: NotionPropertyAsRichText
  JobDescription_CustomFields_CustomCodeTableValue1_: NotionPropertyAsRichText
  JobDescription_PrimaryProfile_: NotionPropertyAsRichText
  JobDescription_ProfessionalCategory_: NotionPropertyAsRichText
  JobDescription_SalaryRange_: NotionPropertyAsRichText
  Link: NotionPropertyAsUrl
  Location_Country_Country_: NotionPropertyAsRichText
  Location_CustomFieldsTranslation_ShortText1_: NotionPropertyAsRichText
  Location_Department_Department_: NotionPropertyAsRichText
  Location_GeographicalArea_GeographicalArea_: NotionPropertyAsRichText
  Location_JobLocation_: NotionPropertyAsRichText
  Location_Region_Region_: NotionPropertyAsRichText
  MainSupervisor: NotionPropertyAsRichText
  /** Automatically filled by Notion */
  MisAJourLe: NotionPropertyAsLastEditedTime
  Name: NotionPropertyAsTitle
  OF_CustomFields_Date1_: NotionPropertyAsRichText
  OF_CustomFields_Date1_Formated: NotionPropertyAsDate
  OfferCustomBlock1_CustomFieldsTranslation_LongText1_: NotionPropertyAsRichText
  OfferCustomBlock1_CustomFields_CustomCodeTableValue3_: NotionPropertyAsRichText
  OfferID: NotionPropertyAsRichText
  Offer_BackOfficeUser_User_: NotionPropertyAsRichText
  Offer_CoordLat_: NotionPropertyAsRichText
  Offer_CoordLong_: NotionPropertyAsRichText
  Offer_CreationUser_: NotionPropertyAsRichText
  Offer_CustomFieldsTranslation_LongText1_: NotionPropertyAsRichText
  Offer_CustomFieldsTranslation_LongText2_: NotionPropertyAsRichText
  Offer_ModificationDate_: NotionPropertyAsRichText
  Offer_ModificationDate_Formated: NotionPropertyAsDate
  Offer_OfferStatus_: NotionPropertyAsRichText
  Offer_Reference_: NotionPropertyAsRichText
  Offer_Specialisation_Specialisation_: NotionPropertyAsRichText
  Origin_BeginningDate_: NotionPropertyAsRichText
  Origin_BeginningDate_Formated: NotionPropertyAsDate
  Origin_CustomFieldsTranslation_ShortText1_: NotionPropertyAsRichText
  Origin_CustomFieldsTranslation_ShortText2_: NotionPropertyAsRichText
  Origin_CustomFieldsTranslation_ShortText3_: NotionPropertyAsRichText
  Origin_Entity_: NotionPropertyAsRichText
  Origin_Entity_With1: NotionPropertyAsRichText
  Origin_Entity_With2: NotionPropertyAsRichText
  Origin_Entity_With3: NotionPropertyAsRichText
  Origin_Entity_With4: NotionPropertyAsRichText
  Origin_Entity_With5: NotionPropertyAsRichText
  Property: NotionPropertyAsRichText
  RequiredLanguage_LanguageLevel_: NotionPropertyAsRichText
  SchedulingData_AutomaticUpdate_: NotionPropertyAsRichText
  SchedulingData_DefaultPublicationBeginDate_: NotionPropertyAsRichText
  SchedulingData_DefaultPublicationBeginDate_Formated: NotionPropertyAsDate
  SchedulingData_DefaultPublicationEndDate_: NotionPropertyAsRichText
  SchedulingData_DefaultPublicationEndDate_Formated: NotionPropertyAsDate
  SchedulingData_UpdateFrequency_: NotionPropertyAsRichText
  hide: NotionPropertyAsCheckbox
  publicationDate: NotionPropertyAsDate
}>
